<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="descriptions" content="Recruitment webpage">
    <meta name="keywords" content="HTML, CSS">
    <meta name="author" content="Nguyen Huy Hoang Viet, Huynh Quoc Hieu, Le Duc Anh">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Careers at MassiveHard</title>
    <link rel="stylesheet" href="styles/style.css">
</head>
<body>
    <header>
        <div class="logo-container">
            <img id="logo" src="images/logo.png" alt="MassiveHard Logo" style="max-width: 50px;">
            <h1>MassiveHard Recruitment Platform</h1>
        </div>
    </header>